FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Expose port for development
EXPOSE 3000 4200 3001 3002 3003 3004 3005 3006 3007

# Development command
CMD ["npm", "run", "start"]